#!/bin/bash
# skeleton-service daemon
# chkconfig: 345 20 80
# description: skeleton-service daemon
# processname: skeleton-service

NAME=skeleton-service
DESC="skeleton-service daemon"
DAEMON_PATH=/opt/$NAME

DROPWIZARD_JAR=/opt/$NAME/lib/$NAME.jar
DROPWIZARD_YAML=/opt/$NAME/conf/hello-world.yml
DAEMON=/usr/bin/java
DAEMONOPTS="-jar $DROPWIZARD_JAR server $DROPWIZARD_YAML"

PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

start() {
    echo "Starting $NAME"
	cd $DAEMON_PATH
	PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
	if [ -z $PID ]; then
        echo "Failed to start $NAME"
    else
        echo $PID > $PIDFILE
        echo "$NAME started"
    fi
}

stop() {
	echo "Stopping $NAME"
        PID=`cat $PIDFILE`
        cd $DAEMON_PATH
    if [ -f $PIDFILE ]; then
        kill -HUP $PID
        echo "$NAME stopped"
        rm -f $PIDFILE
    else
        echo "pidfile $PIDFILE not found"
    fi
}

status() {
	if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "$NAME (pid $PID) process is dead but pidfile exists"
        else
            echo "$NAME (pid $PID) is running"
        fi
    else
        printf "%s\n" "$NAME is not running"
    fi
}

restart() {
	stop
	start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: skeleton-service {status|start|stop|restart}"
        exit 1
        ;;
esac

exit $?