#!/bin/bash

set -e

function helptext {
    echo "Usage: ./generate https://github.com/username/repo-name.git"
    echo ""
    echo "GitHub repo must exist and you must be able to write to it."
}

if [ $# -eq 0 ]
then
    helptext
    exit 1
else
    git clone --bare https://github.com/jenscobie/skeleton-service.git
    cd skeleton-service.git

    git push --mirror $1

    cd ..
    rm -rf skeleton-service.git
fi